export const permissions={
    VIEW_ORDERS:"VIEW_ORDERS",
    CREATE_PRODUCT:"CREATE_PRODUCT",
    DELETE_PRODUCT:"DELETE_PRODUCT",
    UPDATE_PRODUCT:"UPDATE_PRODUCT",
    READ_PRODUCT:"READ_PRODUCT",
    READ_ALL_PRODUCTS:"READ_ALL_PRODUCTS",
    READ_SELLER_ALL_ORDER:"READ_SELLER_ALL_ORDER",
    READ_BUYER_ALL_ORDER:"READ_BUYER_ALL_ORDER",
    READ_SINGLE_ORDER:"READ_SINGLE_ORDER",
    READ_ALL_USERS:"READ_ALL_USERS",
    ADD_BUYER_ROLE:"ADD_BUYER_ROLE",
    CREATE_ARTIST:"CREATE_ARTIST",
    GET_ALL_ARTIST:"GET_ALL_ARTIST",
    DELETE_ARTIST:"DELETE_ARTIST",
    UPDATE_ARTIST:"UPATE_ARTIST",
    GET_CART:"GET_CART",
    ADD_ITEM:"ADD_ITEM",
    

}