export const permissions={
    VIEW_ORDERS:"VIEW_ORDERS",
    CREATE_PRODUCT:"CREATE_PRODUCT",
    DELETE_PRODUCT:"DELETE_PRODUCT",
    UPDATE_PRODUCT:"UPDATE_PRODUCT",
    READ_ALL_PRODUCT:"READ_ALL_PRODUCT",
    READ_SINGLE_PRODUCT:"READ_SINGLE_PRODUCT",
    READ_SELLER_PRODUCT:"READ_SELLER_PRODUCT",
    READ_ALL_USERS:"READ_ALL_USERS",
    CHANGE_PRODUCT_STATUS:"CHANGE_PRODUCT_STATUS",
    ADD_BUYER_ROLE:"ADD_BUYER_ROLE"
    
}